### ISSUE TITLE
I am invisible...

### ISSUE THREAD

**Issue by Pub4Game** [organization/PlayHarder#10]
![image](https://cloud.githubusercontent.com/assets/11244874/10864551/96c0706a-8002-11e5-9731-071bd2dafa9d.png)

This started because of your plugin

**Comment by MrDoni98** [comment]
таже проблема, думал у меня только так (

**Comment by Pub4Game** [comment]
@MrDoni98 лол, ты кто? Напиши вк

**Comment by MrDoni98** [comment]
ахах )) vk.com/mrdoni98

**Comment by HmHmmHm** [comment]
oh...guys i can't understand that language '~';
check again your avatar skin or some scripts

**Comment by MrDoni98** [comment]
why players do not die of hunger when it ends?and he quickly comes to an end

**Comment by MrDoni98** [comment]
ah yes, after the death of the player adds a few extra hearts ...

**Comment by HmHmmHm** [comment]
huh? firstly, vanilla mode also player can't die when hunger bar counted 0,
and secondly, extra hearts is activate when player is level up...

is really when player "after the death of the player add a few extra hearts"?

**Comment by MrDoni98** [comment]
sorry, i dont know ))

**Comment by Pub4Game** [comment]
@HmHmmHm !?
