### ISSUE TITLE
ExperienceOrb Drop Crash

### ISSUE THREAD

**Issue by BobbyTowers** [organization/PlayHarder#3]
PocketMine-MP Crash Dump Fri Oct 30 11:12:11 ACT 2015

Error: Using $this when not in object context
File: /PlayHarder_v1.0-TEST.phar/src/PlayHarder/system/ExperienceSystem
Line: 17
Type: E_ERROR

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: PlayHarder v1.0-TEST

Code:
[8] use PlayHarder\ExperienceOrb;
[9] use pocketmine\Server;
[10] 
[11] class ExperienceSystem {
[12]    public static function dropExpOrb(Position $source, $exp = 1, Vector3 $motion = \null, $delay = 40) {
[13]        $newVersion = \array_map ( "intval", \explode ( ".", "2.0.0" ) );
[14]        $apiVersion = \array_map ( "intval", \explode ( ".", Server::getInstance ()->getApiVersion () ) );
[15]        // Completely different API version
[16]        if ($newVersion [0] > $apiVersion [0]) {
[17]            $this->dropExpOrb__api100 ( $source, $exp, $motion, $delay );
[18]        } else {
[19]            $this->dropExpOrb__api200 ( $source, $exp, $motion, $delay );
[20]        }
[21]    }
[22]    public static function dropExpOrb__api100(Position $source, $exp = 1, Vector3 $motion = \null, $delay = 40) {
[23]        $motion = $motion === \null ? new Vector3 ( \lcg_value () \* 0.2 - 0.1, 0.4, \lcg_value () \* 0.2 - 0.1 ) : $motion;
[24]        $entity = Entity::createEntity ( "ExperienceOrb", $source->getLevel ()->getChunk ( $source->getX () >> 4, $source->getZ () >> 4, \true ), new \pocketmine\nbt\tag\Compound ( "", [ 
[25]                "Pos" => new \pocketmine\nbt\tag\Enum ( "Pos", [ 
[26]                        new \pocketmine\nbt\tag\Double ( "", $source->getX () ),
[27]                        new \pocketmine\nbt\tag\Double ( "", $source->getY () ),

Backtrace:
#0 /src/pocketmine/Server__32bit(0): pocketmine\Server->crashDump(boolean)
#1 /PlayHarder_v1.0-TEST.phar/src/PlayHarder/listener/EventListener(144): PlayHarder\system\ExperienceSystem::dropExpOrb(boolean)
#2 /src/pocketmine/plugin/MethodEventExecutor(36): PlayHarder\listener\EventListener->onEntityDeathEvent(boolean)
#3 /src/pocketmine/plugin/RegisteredListener(96): pocketmine\plugin\MethodEventExecutor->execute(boolean)
#4 /src/pocketmine/plugin/PluginManager(673): pocketmine\plugin\RegisteredListener->callEvent(boolean)
#5 /src/pocketmine/entity/Living(164): pocketmine\plugin\PluginManager->callEvent(boolean)
#6 /ArtificialIntelligent_v0.1.phar/src/onebone/artificialintelligent/entity/BaseEntity(101): pocketmine\entity\Living->kill(boolean)
#7 /src/pocketmine/entity/Entity__32bit(654): onebone\artificialintelligent\entity\BaseEntity->kill(boolean)
#8 /src/pocketmine/entity/Living(67): pocketmine\entity\Entity->setHealth(boolean)
#9 /src/pocketmine/entity/Entity__32bit(613): pocketmine\entity\Living->setHealth(boolean)
#10 /src/pocketmine/entity/Living(106): pocketmine\entity\Entity->attack(boolean)
#11 /ArtificialIntelligent_v0.1.phar/src/onebone/artificialintelligent/entity/BaseEntity(105): pocketmine\entity\Living->attack(boolean)
#12 /src/pocketmine/Player__32bit(2428): onebone\artificialintelligent\entity\BaseEntity->attack(boolean)
#13 /src/pocketmine/network/RakLibInterface(140): pocketmine\Player->handleDataPacket(boolean)
#14 /src/raklib/server/ServerHandler__32bit(90): pocketmine\network\RakLibInterface->handleEncapsulated(boolean)
#15 /src/pocketmine/network/RakLibInterface(79): raklib\server\ServerHandler->handlePacket(boolean)
#16 /src/pocketmine/network/Network__32bit(159): pocketmine\network\RakLibInterface->process(boolean)
#17 /src/pocketmine/Server__32bit(2470): pocketmine\network\Network->processInterfaces(boolean)
#18 /src/pocketmine/Server__32bit(2222): pocketmine\Server->tick(boolean)
#19 /src/pocketmine/Server__32bit(2100): pocketmine\Server->tickProcessor(boolean)
#20 /src/pocketmine/Server__32bit(1701): pocketmine\Server->start(boolean)
#21 /src/pocketmine/PocketMine(464): pocketmine\Server->__construct(boolean)
#22 (1): (boolean)
#23 (0): {main}(boolean)

PocketMine-MP version: 1.6dev #48 [Protocol 34; API 1.13.0]
Git commit: 0000000000000000000000000000000000000000
uname -a: Windows NT SERVERMACHINE 6.1 build 7601 (Windows 7 Business Edition Service Pack 1) i586
PHP Version: 5.6.4
Zend version: 2.6.0
OS : WINNT, win

Loaded plugins:
ArtificialIntelligent 0.1 by onebone for API(s) 1.12.0
ASR 2.0.2 by iJoshuaHD for API(s) 1.12.0
BasicHUD 1.0.6 by aliuly for API(s) 1.12.0
CapsLimit 1.1.0 by deot for API(s) 1.10.0
ClearLagg 1.1.0 by LegendOfMCPE for API(s) 1.0.0
CombinedSlots 1.0.0 by basprohop for API(s) 1.10.0
CustomAlerts 1.6 by EvolSoft for API(s) 1.12.0
CustomAreas 1 by luca28pet for API(s) 1.12.0
EssentialsPE 1.1.3 by LegendsOfMCPE Team for API(s) 1.12.0
ExtendedCreative 1.2.1 by NikoTBC for API(s) 1.13.0
FastTransfer 1.0.2 by shoghicp for API(s) 1.12.0
FurnaceIndicator 1.2 by onebone for API(s) 1.6.0
ItemCloud 1.3 by onebone for API(s) 1.4.0
KeepInventory 1.2.0 by boybook for API(s) 1.0.0
LiveSigns 1.2.1 by aliuly for API(s) 1.12.0
MagicTelePortal 1.3.2 by aliuly for API(s) 1.10.0
ManyWorlds 2.0.3 by aliuly for API(s) 1.10.0
PeacefulSpawn 2.4 by LDX for API(s) 1.3.1, 1.4.0
PlayHarder 1.0-TEST by hm for API(s) 1.13.0, 2.0.0
PocketGuard 2.1.1 by MinecrafterJPN for API(s) 1.10.0
PocketMoney 4.0.1 by MinecrafterJPN, MinecrafterJPN for API(s) 1.10.0
PurePerms 1.2.2 by 64FF00 for API(s) 1.12.0
RandomItem 4.2 by LDX for API(s) 1.0.0, 1.1.0, 1.2.0, 1.3.0, 1.4.0
ServerAuth 2.11 by EvolSoft for API(s) 1.11.0
SimpleMessages 1.2 by Dutok for API(s) 1.0.0
TimeCommander 2 by LDX for API(s) 1.0.0, 1.1.0, 1.2.0, 1.3.0, 1.4.0
TimeRanks 1.0.2 by luca28pet for API(s) 1.12.0
VanishNP 1.0.0 by iksaku for API(s) 1.12.0
VoteBan 1.0.2 by GmWM for API(s) 1.12.0
VoteReward 2.1 by LDX for API(s) 1.0.0, 1.1.0, 1.2.0, 1.3.0
WorldProtect 2.2.0 by aliuly for API(s) 1.10.0, 1.12.0
LightingJoin 1.0.0 by Towers for API(s) 1.13.0
PureChat 1.3.3 by 64FF00 for API(s) 1.11.0

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrNPA1T47a2f0WT3ZkLd/Jh5wtIB+5QYLvbB0sesN2+23QYxVYSF9tyLZuQdvrf3zlHsi0nsMBu
et/bbRf7SDpfOl+SJf5sZEEkGiO33x92u+6g5zYbIk1l2hj92chWCTQ1zm7Prq4urxrNRiSU4nOE
fVJBPGdvs0Wg2HIhYhbLjAUxk9PfhJcxT8aZeMhgyCwIsX9nHPLVe576Ir29d9tO6+bs+qadLHja
UalntXbUSmUi6pw9JCINROyJawIAqjCIkdO9v5qNJMznQQx4q4HQwZO+QL73oSFXglWNk0mF7zKd
fgedD0ynRHp3IosA92RyLdJ7kWKr60Az/nThpxdypdg6R+xPbO9C+yRL8mkYeExlPIMfszz2skDG
zE9lAsOA4s5YqoBgb5XMU0802VvxkLBD5jbZT6AymfbY20hSl0M2mcR5GEIfX4AMAOg7u5pej+hN
srexWP4kUlX052nKV7cRT9gOmzSCOLvn4aTRhBYgE4JiCN4mUKPbdtrOpMF22S4J2y+Q8iT4SqRa
daPRXGQfYtADqInt7LaO4P24QrqzW9IcGJqdDjuRURKKTIQr5gezmUhFnLHj8Qd2r4dh96HpHszY
ji37L86v7IjZjAPE6GrPjAHB0FBbR9V83N7CCNdxQIDahDSLSSh1r7ndN6j+YiIEoyH0B8+g774Y
fdcp0OOLSy/0+ELrKqTZlpV1Sysr+5ZPh8U49i8G81CiBUuYhN78Fkwkx6ln/2ROu8ta8C8Qd9r9
5hc6gFWMChKkkNIiwRSCDHk7o4fRyEsFz4R+I/OreTaaopGdbO9c3IuwMMSTRR7fVVNCsJ+Rk6Mj
1q+P+3cFnkyyFBjebZK4k4kdMOJpBs18PpmgDcs89okl5OIXhnIMShuBvw2YHvC6w6MvYjqL84iw
UO8C0dBGBH+/hOFUgsGIkpMNcXebiHFvOxj/x2CEqJyl3IMA/EvjjcMorFfIOjo+3N72utMg23F2
R48E3taRl3K1OM2jZGcqZSh4vAucvnHZy9NHGEBsjuHh7B5M59y87UB+A5J2QtB5xk4MOqyPRlbU
trnobsiks1DnQmQL6RO9swfh5eAOO73hGrmCLyBoM9Y6krG25VMw6wW11aj2nqJ6JeaIIxV+KeTB
cE2tuutk8giHrSNBT6JGrf8UtTH9uOAxpP90Z7jXe4LSJlcwqTwMNwUbbJDSrt45D+6htthxh/0n
aNR4eQr9kHWOU8gWgRfw8ANUI2EYzKHT7T2Em8pyZCym8H+Hl32Dqm/B0fdcmYCz4zruGle6z2Si
2W4d3QVhWONk7ylBNcrCJYYDlNfwg6n3EYYqahVLj1Dcf0a1w70nZCgwKpG9FzzMFjW0By8UxO09
o6LH0bvOcxbhDJ/hm2cZ9+7qWN2/yxAGz0j5GDObMQRjRBUXu/3u/ldawWPkNoNHLLKlTO86V/zu
PJiiOtIZBG2Ij+shWTPWOlrw2A/FKc/4mGNrnYIJGCm/C4NpR1EYN7H+PQ0sRTtYJ2BYgZhR56Ug
eRZ7PFF5CNnerxMdvFisvQMgqpmDiE9sFcnGsFdQe0y44ZN0PuqfhWzu4ODFwiWp9GAZVae090y+
7Pb3nlSf4aXEXNJao7H/HA3480RahrJzzbIOnkMG1egXkI01q5Aoaxn2ubLB3dsIvwVWKI7T+vR1
3U1no8cLeNzpb6SXAtPtLaxeFdR83hq+LttB6nUgFL4o6J8RD+K/qqZfm405Zj8e4oK0WMeMGm57
6It7GDnNg9BvjPr7sJhNZSY9CT17/WYDKnnq5/baDvSbBxm8Oi/8AwO0teOY9h5hyGOOK/zG5yD2
5VKxjzfs+uzqp7Ori+OT9x8+nrEh1N/EDtsbOi7bKTruse9zWOYLXPv6elmBOgpgZYfewtxdFgz2
h0AiWSRAYNAetvvw9oeIQTJYZA6JPjTeSoUMfPj48QYA9LKE5Xu5kFeopEejNDYY/h9vb1rKhYAO
7zyHYidVWIeaOIqzQWr9BfUKi18EiJhDSQuMYnXfbPgiAbZxFLQpOctObQDOLhB4Li4/xWIoOWpk
fHl98/ny6vwUQEsxhaUayIVLKVDE8fWVLev1VU0yXLB367IFP0q1yPn7061JV2KcTIKLk/EZyHN9
BfkMmKftFSPF9c3x1c2nsS1DY5FliRp1OmCti3za9mTUKbF1UBiQEJJV4L3/dGqJWYKaNRdx2sO6
rKDmPFxtTVCNbjJZ5D7Uxgj78hQ9Jh4PxW+QOFIJuKwQ0zIG3clSIToRx1q4U4oJWjiBnHYeRIFt
2RWsrgeX/MfSgy9kVteC8/VaKKnC4tVi4AW2egIxLj3n87ktQwl7RoZzAU7hX87QwmqyfIsoBfFN
a33xhNp8dSppUFwZTWFq/etQZsoWuQZfN+E1sadcQZxfyGRr81dipM2HGidPe2oxg7nKZHQM9U9d
IhtcF2jNI8/uZXgNjG3NJ23SIFCdkWciD0zkcrlsC+AJ0bezu0YlYyr4IyIS1JLQrUkX5h7v7idi
6+Ih2a8OOSVXHVsIkPRMKVwR8FCBS1Wi1sDrXtl7zCuVNn92I3i0NdFtNrblnzXRUAMPGTQK/wQ3
B4N7YWthvamuie56zfAxuJM335/Uxe99g/hr9HHHaYOjFwTdd5BLblIeq5lILfFq4PUYtFYyqIWc
LwIv2drUFggnE5uN+turC4cCaaeGBTWQpzEsaz7EfuDxTNa0sN60NsnPl4XDLVSFM81FUHABitjk
6wVT/SET0Ukoc9+SsILVRes9L1p/C6IBe5GH5HX0OsEvYi9xYphag6MdFZuJqvMv/XBYYsXp/S8h
kg8xbuTJdGVJXoeve+96mpUrWIPdbauwqNF+UeA2U3gOfn0dzGM79VSwZ0LQ31TuhkBfIf3/SNFb
SQvquODzwLsRoRjLNNNrYqOU9ZY161533cdU43y7aqIsec3sXvB49Vmmoa9qkpTA9aVb7z8jBDCw
JAZeI8tYQICa5eF1wpexJU4dbknUbffrpcPpzzVRemTO3xR2AOVkUmPgVRJVZwIsceyDArUsSd+S
6hO0iDbTf1N/Nf9akexvQTVeXiIQedoPOQyxJbKgdYNz1wMK7nh5KZ+BX/44/rg1w6ujBblqHL02
uNSxdSxknUaphAvIJKsNJWiorQQwvmeU0Py7tGKxVKik4G8rKtHIUCN5KsYijewgVMHWc8xaIB32
371znK3lmFuNDwQuGLAeX10C0kiTUyosIPIVZB8ZYS1kyWwBLaH77e4Xw5ReoRcbFEUpgeHL2Ur4
qrh6TezSm9DHwLYloAVcc3T3Jaty9+slqSgX++OGi69akV8HeM7nQh8is612rcFel6/N4mmeba+6
q5MFCdfZeMGE3QSROJER5N56vqnD7fT5f2qVNbZeY5g4EEz6Tq3JqGHPLDy3v59Skt7CbkolBsj5
E48Dtfg4tsQsQc9s8QV3it/l3yhifdemErhg4oU7KGbWfpKZ+J7bZV0BeWbGfog+X2xtshDZZGIo
lw8vl+BKLOuljwWsFabuV/vWt/hUxc1rHIqWCuMUxnr2t4AauB7tNxa7T60jmltaMNJiItG8rIv2
wkz+mhVjTXRaQ88XWRDPf5RBXFtGW+BnXPJGLqF5a3t5GaGbTLJXLUeggDlZ8GytSiPQ+mq393yR
9lw2t0rAzeDyjtPRUQVabjxRvCFf1dM3l26E5C/80stTED4TaaFjKifaYF6JSLMA64HGm3H5xk5k
PAvmDM+PT9JJ/OZdGrBLL2M9h7nuyDkYuX12fHLDuo47wA4aXyuRaXboHri9LgIjEcl01Qrx29ah
63T7Fwidc4T74tChPvwBzBEPu6jDAUEUrjhbxvBBXYfuEMHLBUjdwoN8h3I2Q4iehNbvuUhXhzK2
QKkHw0yvSGb+obbEEyzmEcbjWOaxJwzlFvcWgbgXEYR+VYzjYSiXrVmI9l7ANGuQCyJIEIakhkVy
WgBmEg9nllJq4ALikydTUWBK7hPTgmeuAy8Ps9WhS+qhgwt4RlCJDD1NHSI4xKO0LbTgQwoMFUwJ
4Vtd8NrA4enZu+NP5zcIRV20E64UDPMP/0l/QDqo5FqK3xf84UmBMj60V1GI9sDQzfA2AZhCDjzh
GQS0CAYisuo0R+tiDBbCbhZCCVYwzXgqWLYQeJpKwQPPmIdqz9hUsCD2wtwXPt5Z2LBExHUtIxg5
QwTrOBWfiSaT0JIqRMmmqeB3bCXz1OBiwYyB6oNZQBRA7SlYEoRUQPxRLEt0HV/MOChesaWM/5Ex
niSCpwxVE+FZb7CAFbDP6JoFyU13LfJknnIfELQnMRq+RjaaxOzNzQICaisEEHAR8nieQynL8GIE
qcw4iQrgPZSAP/iDlIpDTxbCM1LUBwIDhaOLuL0M7oJE+AFvy3TewbcOHvW8lbPbD9eXt8PeQat7
i+NAjSWiEZtAxJpPGkjo80Kg7lgmgZ/YZyAlU1lK+s1wv5+OfOlm0iZxCnzAk8hoSn1Bx1D00S2E
RIBYm31FcgYuIgCuFnnmS3QRXdkjM3oxw7xQKiAFmK8EnSAKCiaP0fkYOjtedDHpit0HnP03ejt0
Ia8vEllF7c31AgZyNFolgTlDVM8cN5hYrsAmIWiDXZCweNsholO6qLaqoQVcToFHC/8ZRZgCEWiA
oVszMF+wEGR2umLGrqC7iUdlq4XocwCKlzGYGPd9lgqlLRH5xDNawA9XEMExJjGwv6lAjYCqxO85
D3F65sE99DXn+Q1JiMe7gFzTgzgoMCC3YHbnc5GOoBUpf8yjKWgf3OtYrWLvhqs7hmfYwKHa2P4J
JwXttRASey1SCTETTAR6qyajGMRMrKIbFZB+QG2KLoGgWiBPISzKY/z4AlDCfU0mBPKAs6XyAQIp
XTwBccj045I11Kpm58MMPRa7oGc2WZD9AzSXpTTKF5glyCrXxrIdkACvGHVRIyRDy0gJikDX1emJ
HPeHUE5Bq5ivmQYzyloYoCIx59NVBtywa82HQ5QDhXOr3R7vYQXEFWmaYeow2c+AFCllFoCtQMwS
+FEDscwgYBQU9dyDJDmZ7FyCEBL9BBUGdObEpE6nIzZwSQj2hoJ0BpGH+//PBcCCp2C/h7aItKFY
CiRlAjR7hTg9ioUGaWnaLpgBuLWP00k9WmB6Qhs1RVAJC7cYnAF4REd8SgTNOpQTIQVXdCvdbUK5
DnGAoVdOYzwWSVyiu2J2of7tzd7oqaY2BGUnwsMkpEgnyKyeDT22lACir0hUJSeUWFpQtfsoR0bs
nhZ7ztMpKLvlyTDU9RIa9KNqpblDVswYZsaAn0Q8zind2VxAKZCD1ew2C/9bMxtjNzqGzWaFH0aV
PbbZpc419KYgF8g89EtGAvDWZcwq1tFIWEKcg4BDx9EysjfvyOw24hAZix5dCjVLZVSEMxxr2lt2
BBgxrNsN7hszdeu28IgBWeOwbvXwRpPS+qYDXBR8CIicYemO0jBdZTbJF1JI/kp3amH+xTqiwoWo
imk2jnIwNHyeSj1sffow4GKVoofZGDQV020LMlPQb3lQLQsttbGFghA2VBnui7gmsTlBXdZNYBuh
TjtTnkE9jnmfToVDtgGDMgGMPFBXhaZVx62pKBOQ8MtEY0y2aEHXT1cZ4m6ylmtZMyYaItvKClZG
0EOHlSqvUYWNScXXsc5MoB4KQMNSm72HVQOo9xDqUDDck/GnJowFBqYQgJaBny10iCT/LtG3CD1E
dpOEq/SsSC9W1zY79sGfFjyc4Rd+XTHQPUJDCEhq+5Ox7ZBlJrRwFZMCtQ1dxsKKg4dN7ddI15xI
bjOwGkGWjWn10zgeF0m5Kpex3sBBtB+DtXKctMyrXf7AskdM8/nI5PcjvCEJ7kNTqbCCo+aielMU
xhaiqOomZiZGzK1KMsU6eEUzB3PpzD2tWdxoVRbRYsFUK9lFUa8h3yCJXqxQV2NcKC7Nt7796FON
SENaesiIRdA0N6U8CETbAsjuPZ6h0zGJ1/BD4MTFUGaRB2Vmm9yQi9LMvfl4eXM2YhR04T8vT/Gq
Liidbn/j5jlOHbFnKJfslVXncW22PCjhIZAYWcmIKCMBJ2g0GRpO1zEZBCOZTkxoRbh+RLjJRsaE
6uAihOmy8xqdFQWcciUsYjsu+MkjVJqsi1dnH2sQmdfeJZdVwuaCzOEGMeOqxmwrMAFxSdPD1K9n
ktaP1cISwwAtObBSwWDAwyVfKY3b4LHsqBa+yYyOI5nHdvxXpj4qmED2ERtW5xCa8dHw+/hQntJ9
VuJd46gnHVDMo4PJuGKhV3BToZFNxQzjEG1VYLzCWSiR6g0MK+5R/Lnm95BxcQ2Ix+z/ELjOSVZm
TW4SUVnNUJiY0T5iERNNDJvlIXWTCgy1Ze5Q62MSOBEpLoTBLABtoajfJC45tGcoHqGlRBQoMbuU
0hd5RM8EarOYiQv+wPi6VszlHOFXxrA5EVewqs+VNcrMATe8kYPqkcbmsL8eTNtErTzxwQ6t5aiH
J5m1FeFidp3vav1UsN7e5N3EviUPaDEMC99cmMk148nlCd5SMFVGnFdjS2Si73uhavQzZqU1xJOY
/LEFykOm9WZYi4wIBEejjPACD+5zWDAMDLjdNGK6qiumE+/r5AlUObrU07ZIYUNXGAaXwWKoFW9L
jmTqMB5NAzB5ejPbXHoVPNIxCBfseM2ZaajOrMY8tNma+t3awYBBLdxTKcMcQco0UoMmiySIZ7Ia
vZA470SzbW2xQflDDMYyXkVY3ZNvKNCtKjnF9YppZlUzcQx2xhmfzyHrmPV3ubWBpSHeBb97QhzN
EOJTjzGEGtN2TPO7MRwsQjeP9BSkccukZav0I7BM7I2ZE9yqo70jEcoEM1UT3kEK3BjLiiIMipIZ
FMkCFA65KcYcj51MWs3p955wG0nxWyqs+iGHUlNlOrkV0c5gw1nSzQV+ta4Y/HL+iFrCAHKNnpqz
B47JVr9gtQIEDBejgh1qAntXmQTr/gUfWxx/2wMCfkWMOggWNYi9y0lSFGsFvWAr9oRpJfbYpimt
bCmFKSoXUO4IqogAGDX53WKdqDIdh/UzbiKPWN/p01tJb8TenR/fjLrf7TUHBw9us/fQa3a/c7/z
IRHrwLWD35A8DDKH+w6bg5kr/dYf7NK2ssDz1qgS+nZ9AnnIuqw29aAYWTRGNAXNBm40xj5PK4D+
JTjmDa3OGgzZY162zYIwwyMAeA1Nf2KcZUnZugDv09+ooCHA6qhs+k3VDoJCIbdKsrL1enxOOPED
rfSnXokk8dKKsSsxMysxaH/7ATQ57fKe4wz2h/v73BvsO960u7/f8/pd+Mc9mPmOcBx/0Buwtw38
GKP0VyiDDn+Bi0/fXEtZo5X6PaSLfeaJDfCMldsCV2At/AzTdQZODx6J/Ky31xN84PuDQW9/b+j2
nSHfd7pd3p/u895ev+/uT7t9RxD5TN6JGMJ7Wl7i+yNI9EWFrr5SqK806i+g8PyAnweKOZERNjlO
z3W7B9A+Pr00XwP7+q7leIETWl6i08c8fr44L6ktff+hxGfjhmdctFiMAWSZBpkF+Sz4HcQMPUl0
Twbq4goFaSsoe+NLJnr6fmZL86fI2VU1ZKq3w0vAitPnENec7EvMboaRyXXodx9Ft77MIFiUpCJt
cwbHvzHxXI4p60GXPVQP0n+Hd0MeaLVjvjIPG3/99b/vCQzk
===END CRASH DUMP===

**Comment by HmHmmHm** [comment]
i'll fix that problem

**Comment by HmHmmHm** [comment]
Fixed 32fad3ddc30be0cc5bdf3d42bf2700b9a7bef798
