### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Pub4Game** [organization/PlayHarder#6]
I am unable to get more than 1 level of experience

**Comment by MrDoni98** [comment]
kill mobs for get more

**Comment by HmHmmHm** [comment]
try this
- Kill mobs
- Block break (random)
- Kill player

**Comment by Pub4Game** [comment]
So I pick up particles of experience, but they do not count

**Comment by HmHmmHm** [comment]
really? can you more infomation?
i can't reproduce that problem

**Comment by Pub4Game** [comment]
I just break the blocks and collect the particles experience.... I was immediately given a level 1 and the following selected particles are not counted and remains always level 1

**Comment by HmHmmHm** [comment]
oh i see that error i'll check it

**Comment by HmHmmHm** [comment]
Fixed 7b48902

**Comment by Pub4Game** [comment]
thanks
